
-- =========================================
-- EKANI CRM - Full Database Schema
-- =========================================

-- Extensions
create extension if not exists pgcrypto;

-- -----------------------------------------
-- ENUMS
-- -----------------------------------------
do $$
begin
  if not exists (select 1 from pg_type where typname = 'user_role') then
    create type public.user_role as enum ('sales', 'admin');
  end if;

  if not exists (select 1 from pg_type where typname = 'lead_status') then
    create type public.lead_status as enum (
      'New Lead',
      'Contacted',
      'Follow-Up',
      'Meeting Scheduled',
      'Nurture',
      'Deal Confirmed – Pending Payment',
      'Paid – In Production',
      'Client Review',
      'Closed – Delivered',
      'Closed Lost'
    );
  end if;
end $$;

-- -----------------------------------------
-- TABLE: sales_executives
-- -----------------------------------------
create table if not exists public.sales_executives (
  user_id uuid primary key references auth.users (id) on delete cascade,
  full_name text not null,
  email text not null unique,
  civil_id text,
  contact_number text,
  role public.user_role not null default 'sales',
  date_joined date not null default current_date,
  commission_default_percentage numeric(6,2) not null default 0,
  active_status boolean not null default true,
  clients_visited_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_sales_executives_role on public.sales_executives(role);
create index if not exists idx_sales_executives_active on public.sales_executives(active_status);

-- updated_at trigger function
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists trg_sales_executives_updated_at on public.sales_executives;
create trigger trg_sales_executives_updated_at
before update on public.sales_executives
for each row execute function public.set_updated_at();

-- -----------------------------------------
-- TABLE: leads
-- -----------------------------------------
create table if not exists public.leads (
  lead_id bigint generated by default as identity primary key,
  date_added date not null default current_date,
  sales_exec_id uuid not null references public.sales_executives(user_id) on delete restrict,
  lead_source text,
  client_business_name text not null,
  client_contact_person text,
  phone_number text,
  whatsapp_number text,
  email text,
  governorate text,
  area text,
  business_full_address text,
  domain_status text,
  decision_maker_confirmed boolean not null default false,
  budget_confirmed boolean not null default false,
  timeline_days integer,
  solution_selected text,
  add_ons text,
  quoted_amount_kd numeric(12,3) not null default 0,
  final_agreed_amount_kd numeric(12,3) not null default 0,
  intake_form_completed boolean not null default false,
  payment_link_sent boolean not null default false,
  payment_received boolean not null default false,
  invoice_generated boolean not null default false,
  production_deadline date,
  preview_sent_date date,
  go_live_date date,
  followup_7day_completed boolean not null default false,
  refund_cancellation boolean not null default false,
  escalation_required boolean not null default false,
  remarks text,
  status public.lead_status not null default 'New Lead',
  followup_due_date date,
  commission_percentage numeric(6,2) not null default 0,
  days_to_close integer generated always as (
    case when go_live_date is null then null else (go_live_date - date_added) end
  ) stored,
  commission_eligible boolean generated always as (
    (payment_received = true) and (refund_cancellation = false)
  ) stored,
  commission_amount_kwd numeric(12,3) generated always as (
    case
      when (payment_received = true) and (refund_cancellation = false)
        then round(final_agreed_amount_kd * (commission_percentage / 100.0), 3)
      else 0
    end
  ) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_leads_sales_exec on public.leads(sales_exec_id);
create index if not exists idx_leads_status on public.leads(status);
create index if not exists idx_leads_followup_due on public.leads(followup_due_date);
create index if not exists idx_leads_date_added on public.leads(date_added);

drop trigger if exists trg_leads_updated_at on public.leads;
create trigger trg_leads_updated_at
before update on public.leads
for each row execute function public.set_updated_at();

-- -----------------------------------------
-- SECURITY DEFINER: is_admin()
-- -----------------------------------------
create or replace function public.is_admin(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.sales_executives se
    where se.user_id = uid
      and se.role = 'admin'
      and se.active_status = true
  );
$$;

-- -----------------------------------------
-- RLS
-- -----------------------------------------
alter table public.sales_executives enable row level security;
alter table public.leads enable row level security;

-- SALES_EXECUTIVES policies
create policy "se_self_read"
on public.sales_executives
for select
to authenticated
using (
  user_id = auth.uid()
  or public.is_admin(auth.uid())
);

create policy "se_self_update"
on public.sales_executives
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "se_admin_insert"
on public.sales_executives
for insert
to authenticated
with check (
  user_id = auth.uid()
  or public.is_admin(auth.uid())
);

create policy "se_admin_update"
on public.sales_executives
for update
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "se_admin_delete"
on public.sales_executives
for delete
to authenticated
using (public.is_admin(auth.uid()));

-- LEADS policies
create policy "leads_rep_read"
on public.leads
for select
to authenticated
using (
  sales_exec_id = auth.uid()
  or public.is_admin(auth.uid())
);

create policy "leads_rep_insert"
on public.leads
for insert
to authenticated
with check (
  sales_exec_id = auth.uid()
  or public.is_admin(auth.uid())
);

create policy "leads_rep_update"
on public.leads
for update
to authenticated
using (
  sales_exec_id = auth.uid()
  or public.is_admin(auth.uid())
)
with check (
  sales_exec_id = auth.uid()
  or public.is_admin(auth.uid())
);

create policy "leads_admin_delete"
on public.leads
for delete
to authenticated
using (public.is_admin(auth.uid()));

-- -----------------------------------------
-- VIEWS
-- -----------------------------------------
create or replace view public.v_my_leads_export as
select
  l.lead_id,
  l.date_added,
  se.full_name as sales_executive_name,
  l.lead_source,
  l.client_business_name,
  l.client_contact_person,
  l.phone_number,
  l.whatsapp_number,
  l.email,
  l.governorate,
  l.area,
  l.business_full_address,
  l.domain_status,
  l.decision_maker_confirmed,
  l.budget_confirmed,
  l.timeline_days,
  l.solution_selected,
  l.add_ons,
  l.quoted_amount_kd,
  l.final_agreed_amount_kd,
  l.intake_form_completed,
  l.payment_link_sent,
  l.payment_received,
  l.invoice_generated,
  l.production_deadline,
  l.preview_sent_date,
  l.go_live_date,
  l.followup_7day_completed,
  l.refund_cancellation,
  l.escalation_required,
  l.remarks,
  l.days_to_close,
  l.followup_due_date,
  l.commission_percentage,
  l.commission_eligible,
  l.commission_amount_kwd,
  l.status,
  l.created_at
from public.leads l
join public.sales_executives se on se.user_id = l.sales_exec_id;

create or replace view public.v_admin_leads_export as
select * from public.v_my_leads_export;

create or replace view public.v_commission_payout_report as
select
  l.lead_id,
  l.date_added,
  se.full_name as sales_executive_name,
  se.email as sales_executive_email,
  l.client_business_name,
  l.final_agreed_amount_kd,
  l.commission_percentage,
  l.commission_eligible,
  l.commission_amount_kwd,
  l.payment_received,
  l.refund_cancellation,
  l.status,
  l.go_live_date
from public.leads l
join public.sales_executives se on se.user_id = l.sales_exec_id;

-- -----------------------------------------
-- Auto-create sales_executive on signup
-- First user becomes admin
-- -----------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  _role public.user_role;
  _name text;
  _email text;
begin
  -- First user ever becomes admin
  if (select count(*) from public.sales_executives) = 0 then
    _role := 'admin';
  else
    _role := 'sales';
  end if;

  _name := coalesce(
    new.raw_user_meta_data ->> 'full_name',
    new.raw_user_meta_data ->> 'name',
    split_part(new.email, '@', 1)
  );
  _email := new.email;

  insert into public.sales_executives (user_id, full_name, email, role)
  values (new.id, _name, _email, _role)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();
